apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc-app
  template:
    metadata:
      labels:
        app: abc-app
    spec:
      containers:
      - name: abc-app
        image: thankidivyesh/abctechnologies:latest
        ports:
        - containerPort: 8080
